import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/modules/auth_provider";
import WebSocketProvider from "@/modules/websocket_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthContextProvider>
        <WebSocketProvider>
          {children}
        </WebSocketProvider>
      </AuthContextProvider>  
      </body>
    </html>
  );
}
